version: '2'
services:
  server:
    image: lacsap/cmangos-wotlk
    #build: .
    container_name: cmangos-wotlk-server
    ports:
      - "8085:8085"
      - "3724:3724"
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - /docker_data/cmangos-wotlk:/home/mangos/run/etc/
    environment:
      MYSQL_ROOT_PASSWORD: toor

  db:
    image: mysql
    container_name: cmangos-wotlk-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor

  register:
    image: lacsap/cmangos-web-register
    container_name: cmangos-wotlk-register
    ports:
      - "8080:80"
    links:
      - db:db
